name: Java CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B verify "-Dspring.profiles.active=ci"